/**
 * TA-MRZ tests (§4.2, §7, §11.3 #32/#34/#35, §11.5 #61).
 *
 * Every fixture is built here, in code, from the ICAO 9303 field layout — including its
 * check digits, which are computed by an implementation written independently of the one
 * under test (transcribed from the spec, not imported). That matters: if the fixtures were
 * generated by the module they validate, a wrong weight cycle would produce self-consistent
 * nonsense and every test would still pass. As a cross-check the two implementations are
 * also asserted to agree, and against the published ICAO specimen values.
 *
 * No test reads a file or depends on another tier.
 */

import { describe, expect, it } from 'vitest';

import { DETERMINISTIC_CONFIDENCE } from '@/types/contract';
import {
  computeCheckDigit,
  detectMrzBand,
  extractMrz,
  sanitizeMrzLine,
  MRZ_CHARACTER_SET,
} from '@/pipeline/tier-a-mrz';

// ---------------------------------------------------------------------------
// Independent check-digit implementation, transcribed from ICAO 9303 §4.9
// ---------------------------------------------------------------------------

/** `<` = 0, `0`–`9` = 0–9, `A`–`Z` = 10–35; weights repeat 7, 3, 1. */
function icaoCheckDigit(field: string): string {
  const weights = [7, 3, 1];
  let total = 0;
  for (let index = 0; index < field.length; index++) {
    const character = field[index];
    let value: number;
    if (character === '<') value = 0;
    else if (character >= '0' && character <= '9') value = character.charCodeAt(0) - '0'.charCodeAt(0);
    else value = character.charCodeAt(0) - 'A'.charCodeAt(0) + 10;
    total += value * weights[index % 3];
  }
  return String(total % 10);
}

const pad = (value: string, width: number) => value.padEnd(width, '<');

// ---------------------------------------------------------------------------
// Fixture builders — one per ICAO layout
// ---------------------------------------------------------------------------

interface Holder {
  documentNumber: string;
  issuingState: string;
  nationality: string;
  dob: string;
  sex: string;
  expiry: string;
  names: string;
  personalNumber?: string;
}

const ANNA: Holder = {
  documentNumber: 'L898902C3',
  issuingState: 'GBR',
  nationality: 'GBR',
  dob: '740812',
  sex: 'F',
  expiry: '120415',
  names: 'ERIKSSON<<ANNA<MARIA',
  personalNumber: 'ZE184226B',
};

/** TD3, 2×44 — the passport booklet layout (§4.2). */
function buildTd3(holder: Holder, expiry = holder.expiry): [string, string] {
  const { documentNumber, issuingState, nationality, dob, sex, names } = holder;
  const documentNumberCd = icaoCheckDigit(documentNumber);
  const dobCd = icaoCheckDigit(dob);
  const expiryCd = icaoCheckDigit(expiry);
  const personal = pad(holder.personalNumber ?? '', 14);
  const personalCd = icaoCheckDigit(personal);

  const line1 = pad(`P<${issuingState}${names}`, 44);
  const body =
    `${documentNumber}${documentNumberCd}${nationality}${dob}${dobCd}${sex}` +
    `${expiry}${expiryCd}${personal}${personalCd}`;
  // The composite digit covers line 2 positions 1-10, 14-20 and 22-43.
  const composite = icaoCheckDigit(
    `${documentNumber}${documentNumberCd}${dob}${dobCd}${expiry}${expiryCd}${personal}${personalCd}`,
  );
  return [line1, `${body}${composite}`];
}

/** TD2, 2×36 — some national ID cards (FR, RO). */
function buildTd2(holder: Holder, expiry = holder.expiry): [string, string] {
  const { documentNumber, issuingState, nationality, dob, sex, names } = holder;
  const documentNumberCd = icaoCheckDigit(documentNumber);
  const dobCd = icaoCheckDigit(dob);
  const expiryCd = icaoCheckDigit(expiry);
  const optional = pad('', 7);

  const line1 = pad(`I<${issuingState}${names}`, 36);
  const body =
    `${documentNumber}${documentNumberCd}${nationality}${dob}${dobCd}${sex}` +
    `${expiry}${expiryCd}${optional}`;
  const composite = icaoCheckDigit(
    `${documentNumber}${documentNumberCd}${dob}${dobCd}${expiry}${expiryCd}${optional}`,
  );
  return [line1, `${body}${composite}`];
}

/** TD1, 3×30 — credit-card-sized national IDs and residence permits (§11.3 #35). */
function buildTd1(holder: Holder, expiry = holder.expiry): [string, string, string] {
  const { documentNumber, issuingState, nationality, dob, sex, names } = holder;
  const documentNumberCd = icaoCheckDigit(documentNumber);
  const dobCd = icaoCheckDigit(dob);
  const expiryCd = icaoCheckDigit(expiry);
  const optional2 = pad('', 11);

  const line1 = pad(`I<${issuingState}${documentNumber}${documentNumberCd}`, 30);
  const line2Body = `${dob}${dobCd}${sex}${expiry}${expiryCd}${nationality}${optional2}`;
  // The composite digit covers line 1 positions 6-30 plus line 2 positions 1-7, 9-15, 19-29.
  const composite = icaoCheckDigit(
    `${line1.slice(5, 30)}${dob}${dobCd}${expiry}${expiryCd}${optional2}`,
  );
  return [line1, `${line2Body}${composite}`, pad(names, 30)];
}

const TODAY = new Date(Date.UTC(2026, 7, 9)); // 2026-08-09, pinned: century resolution needs it.

const expiryOf = (result: ReturnType<typeof extractMrz>) =>
  result.candidates.find((candidate) => candidate.role === 'EXPIRY');

// ---------------------------------------------------------------------------

describe('check digits (§4.2)', () => {
  it('matches the published ICAO 9303 specimen values', () => {
    expect(computeCheckDigit('L898902C3')).toBe('6');
    expect(computeCheckDigit('740812')).toBe('2');
    expect(computeCheckDigit('120415')).toBe('9');
  });

  it('agrees with an independent transcription of the 7-3-1 rule', () => {
    const samples = [
      'L898902C3',
      'D23145890',
      '740812',
      '120415',
      'ZE184226B<<<<<',
      '<<<<<<<<<<<<<<',
      'AB1<CD2<EF3',
      '000000',
    ];
    for (const sample of samples) {
      expect(computeCheckDigit(sample)).toBe(icaoCheckDigit(sample));
    }
  });

  it('treats < as 0 and letters as 10-35', () => {
    expect(computeCheckDigit('<')).toBe('0');
    expect(computeCheckDigit('A')).toBe(String((10 * 7) % 10));
    expect(computeCheckDigit('Z')).toBe(String((35 * 7) % 10));
  });
});

describe('band detection (§7)', () => {
  it('constrains the band to [A-Z0-9<], reading a lowercase c as the filler it is', () => {
    // OCR-B has no lowercase, so lowercase c in a band is a misread `<` (§4.2).
    expect(sanitizeMrzLine('P<GBRERIKSSONccANNA')).toBe('P<GBRERIKSSON<<ANNA');
    expect(sanitizeMrzLine('P<GBR ERIKSSON <<ANNA')).toBe('P<GBRERIKSSON<<ANNA');
    expect(sanitizeMrzLine('P«GBR')).toBe('P<<GBR');
    expect(MRZ_CHARACTER_SET.test(sanitizeMrzLine('p<gbr!!123'))).toBe(true);
  });

  it('picks the band at the bottom of a page full of other text (§7)', () => {
    const [line1, line2] = buildTd3(ANNA);
    const band = detectMrzBand({
      source: [
        { text: 'PASSPORT / PASSEPORT', bbox: [0.1, 0.05, 0.9, 0.1] },
        { text: 'Surname / Nom  ERIKSSON', bbox: [0.1, 0.3, 0.9, 0.35] },
        { text: line1, bbox: [0.05, 0.86, 0.95, 0.9] },
        { text: line2, bbox: [0.05, 0.91, 0.95, 0.95] },
      ],
    });
    expect(band?.format).toBe('TD3');
    expect(band?.lines).toEqual([line1, line2]);
  });

  it('classifies layouts by line width, not by guessing', () => {
    expect(detectMrzBand({ source: buildTd1(ANNA).join('\n') })?.format).toBe('TD1');
    expect(detectMrzBand({ source: buildTd2(ANNA).join('\n') })?.format).toBe('TD2');
    expect(detectMrzBand({ source: buildTd3(ANNA).join('\n') })?.format).toBe('TD3');
  });

  it('does not pad a truncated band up to a legal width', () => {
    // Padding a 42-char read to 44 would change the composite digit's input and
    // manufacture either a false pass or a false tamper signal.
    const [line1, line2] = buildTd3(ANNA);
    expect(detectMrzBand({ source: [line1.slice(0, 42), line2.slice(0, 42)] })).toBeNull();
  });

  it('ignores prose that happens to be the right length', () => {
    const sentence = 'THE QUICK BROWN FOX JUMPED OVER THE LAZY DOGS!'.slice(0, 44);
    expect(detectMrzBand({ source: [sentence, sentence] })).toBeNull();
  });
});

describe('clean reads', () => {
  it('reads a TD3 passport at 0.99 with every check digit validated (§11.3 #32)', () => {
    const result = extractMrz({ source: buildTd3(ANNA, '310415').join('\n'), today: TODAY });

    expect(result.abstained).toBe(false);
    expect(result.tier).toBe('TA_MRZ');
    expect(result.checksum_validated).toBe(true);
    expect(result.issuer).toBe('GBR');
    expect(result.cost_usd).toBe(0);
    expect(expiryOf(result)).toMatchObject({
      raw: '310415',
      iso: '2031-04-15',
      confidence: DETERMINISTIC_CONFIDENCE,
    });
    expect(result.candidates.find((candidate) => candidate.role === 'DATE_OF_BIRTH')?.iso).toBe(
      '1974-08-12',
    );
    expect(result.checksum_detail).toContain('all');
    expect(result.reason_codes).toEqual([]);
    expect(result.anomalies).toEqual([]);
  });

  it('resolves an expired passport into the PAST, which is the case we exist to catch (§11.4 #50)', () => {
    // G8: the brief's "expiry always resolves to the future" rule would turn this 2019
    // passport into a 2119 one and pass it.
    const result = extractMrz({ source: buildTd3(ANNA, '190315').join('\n'), today: TODAY });

    expect(result.abstained).toBe(false);
    expect(expiryOf(result)?.iso).toBe('2019-03-15');
    expect(expiryOf(result)!.iso! < '2026-08-09').toBe(true);
    // The raw field is retained so a century-policy change stays auditable (§11.4 #53).
    expect(expiryOf(result)?.raw).toBe('190315');
  });

  it('handles a TD1 residence permit as a first-class layout (§11.3 #35)', () => {
    const result = extractMrz({ source: buildTd1(ANNA, '290630'), today: TODAY });

    expect(result.abstained).toBe(false);
    expect(result.checksum_validated).toBe(true);
    expect(expiryOf(result)?.iso).toBe('2029-06-30');
    expect(result.grounding_tokens).toHaveLength(3);
    expect(result.grounding_tokens?.every((line) => line.length === 30)).toBe(true);
  });

  it('handles a TD2 card', () => {
    const result = extractMrz({ source: buildTd2(ANNA, '271130'), today: TODAY });

    expect(result.abstained).toBe(false);
    expect(expiryOf(result)?.iso).toBe('2027-11-30');
  });

  it('reads a non-US passport unchanged — the MRZ is an international standard (§11.3 #34)', () => {
    const german = { ...ANNA, issuingState: 'DEU', nationality: 'DEU', names: 'MUSTERMANN<<ERIKA' };
    const result = extractMrz({ source: buildTd3(german, '330228').join('\n'), today: TODAY });

    expect(result.abstained).toBe(false);
    expect(result.issuer).toBe('DEU');
    expect(expiryOf(result)?.iso).toBe('2033-02-28');
  });

  it('survives OCR whitespace and lowercase filler in the band', () => {
    const [line1, line2] = buildTd3(ANNA, '310415');
    const noisy = [line1.replace(/<</g, 'cc').replace(/^(.{10})/, '$1 '), `${line2.slice(0, 20)} ${line2.slice(20)}`];
    const result = extractMrz({ source: noisy, today: TODAY });

    expect(result.abstained).toBe(false);
    expect(expiryOf(result)?.iso).toBe('2031-04-15');
  });
});

describe('check digit failure is a finding, not a parse error (§7, §11.5 #61)', () => {
  /** Bump one character of a line to break exactly one digit. */
  const mutate = (line: string, index: number) =>
    line.slice(0, index) + String((Number(line[index]) + 1) % 10) + line.slice(index + 1);

  it('abstains with CHECKSUM_FAILED and names the expiry digit', () => {
    const [line1, line2] = buildTd3(ANNA, '310415');
    const result = extractMrz({ source: [line1, mutate(line2, 27)], today: TODAY });

    expect(result.abstained).toBe(true);
    expect(result.reason_codes).toEqual(['CHECKSUM_FAILED']);
    expect(result.anomalies).toEqual(['CHECKSUM_FAILED']);
    expect(result.checksum_validated).toBe(false);
    expect(result.checksum_detail).toContain('expirationDateCheckDigit');
    expect(result.checksum_detail).toContain('line 2 position 28');
    expect(result.checksum_detail).toMatch(/found "\d", expected "\d"/);
    // No value escapes on a failed checksum — we are not entitled to guess whether the
    // failure was tampering or a misread.
    expect(result.candidates).toEqual([]);
  });

  it('names the document-number digit when that is the one that fails', () => {
    const [line1, line2] = buildTd3(ANNA, '310415');
    const result = extractMrz({ source: [line1, mutate(line2, 9)], today: TODAY });

    expect(result.reason_codes).toEqual(['CHECKSUM_FAILED']);
    expect(result.checksum_detail).toContain('documentNumberCheckDigit');
    expect(result.checksum_detail).not.toContain('expirationDateCheckDigit');
  });

  it('fails a TD1 band the same way — the layout does not change the rule', () => {
    const [line1, line2, line3] = buildTd1(ANNA, '290630');
    const result = extractMrz({ source: [line1, mutate(line2, 13), line3], today: TODAY });

    expect(result.abstained).toBe(true);
    expect(result.reason_codes).toEqual(['CHECKSUM_FAILED']);
    expect(result.checksum_detail).toContain('expirationDateCheckDigit');
  });

  it('distinguishes a likely OCR misread from a likely alteration in the detail (§8.6)', () => {
    // O-for-0 inside the birth date: illegal where it sits, so it is a read error.
    const [line1, line2] = buildTd3(ANNA, '310415');
    const misread = `${line2.slice(0, 13)}74O812${line2.slice(19)}`;
    const result = extractMrz({ source: [line1, misread], today: TODAY });

    expect(result.abstained).toBe(true);
    expect(result.reason_codes).toEqual(['CHECKSUM_FAILED']);
    expect(result.checksum_detail).toContain('O→0');
    expect(result.checksum_detail).toContain('misread');
    // Flagged, never corrected.
    expect(result.candidates).toEqual([]);
  });

  it('does not claim a misread when the digits are simply wrong', () => {
    const [line1, line2] = buildTd3(ANNA, '310415');
    const result = extractMrz({ source: [line1, mutate(line2, 27)], today: TODAY });
    expect(result.checksum_detail).not.toContain('misread');
  });
});

describe('abstention (§5)', () => {
  it('abstains cleanly when there is no band at all', () => {
    const result = extractMrz({
      source: 'UTILITY BILL\nAccount 123456\nStatement period 01 JAN 2026 to 31 JAN 2026',
      today: TODAY,
    });

    expect(result.abstained).toBe(true);
    expect(result.reason_codes).toEqual(['NO_MACHINE_READABLE_REGION']);
    expect(result.candidates).toEqual([]);
    expect(result.checksum_validated).toBeNull();
  });

  it('never throws, whatever it is handed', () => {
    for (const source of ['', '\n\n\n', '<'.repeat(44), ['<'.repeat(44), '<'.repeat(44)]]) {
      expect(() => extractMrz({ source, today: TODAY })).not.toThrow();
    }
  });

  it('abstains rather than inventing a date when a valid-checksum field is not a calendar date', () => {
    // Month 99 with a correct check digit: the band is internally consistent and still
    // unusable. Silence beats a fabricated 2099.
    const result = extractMrz({ source: buildTd3(ANNA, '319915').join('\n'), today: TODAY });

    expect(result.abstained).toBe(true);
    expect(result.candidates).toEqual([]);
    expect(result.reason_codes).toEqual(['NO_DATES_FOUND']);
  });
});
